services:
  upgrade-fagoon-dev:
    build: .
    image: upgrade-fagoon:dev
    container_name: upgrade-fagoon_dev_container
    ports:
      - "8004:2321"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    restart: unless-stopped