from typing import Optional
from pydantic import BaseModel, Field


class GenerateTextRequest(BaseModel):
    prompt: str = Field(..., description="The prompt for AI text generation.")


class GenerateTextResponse(BaseModel):
    generated_text: str = Field(..., description="The text generated by the AI.")
