"""Add usage tracking tables

Revision ID: 0b463d51fdf2
Revises: c3d4e5f6a7b8
Create Date: 2026-01-17 04:25:25.868793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b463d51fdf2'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_usage_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('usage_by_provider', sa.JSON(), nullable=True),
    sa.Column('top_workflows', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monthly_user_period', 'monthly_usage_summaries', ['user_id', 'period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_monthly_usage_summaries_user_id'), 'monthly_usage_summaries', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_execution', 'usage_records', ['execution_id'], unique=False)
    op.create_index('idx_usage_provider_model', 'usage_records', ['provider', 'model'], unique=False)
    op.create_index('idx_usage_user_created', 'usage_records', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_usage_workflow', 'usage_records', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_execution_id'), 'usage_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_records_workflow_id'), 'usage_records', ['workflow_id'], unique=False)
    op.create_table('user_quotas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_execution_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_limit_usd', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('current_tokens', sa.Integer(), nullable=False),
    sa.Column('current_executions', sa.Integer(), nullable=False),
    sa.Column('current_cost_usd', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quotas_user_id'), 'user_quotas', ['user_id'], unique=True)
    op.alter_column('connection', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('knowledgedocument', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('knowledgedocument', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('knowledgedocument', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('knowledgedocument', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('knowledgedocument', sa.Column('char_count', sa.Integer(), nullable=True))
    op.add_column('knowledgedocument', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('knowledgedocument', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('knowledgedocument', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('knowledgedocument', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_knowledge_content_hash', 'knowledgedocument', ['content_hash'], unique=False)
    op.create_index('ix_knowledge_filename_chunk', 'knowledgedocument', ['filename', 'chunk_index'], unique=False)
    op.create_index('ix_knowledge_user_filename', 'knowledgedocument', ['user_id', 'filename'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_filename'), 'knowledgedocument', ['filename'], unique=False)
    op.alter_column('nodeexecutiontrace', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_trace_execution_created', 'nodeexecutiontrace', ['execution_id', 'created_at'], unique=False)
    op.create_index('ix_trace_node_status', 'nodeexecutiontrace', ['node_id', 'status'], unique=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_user_active_created', 'user', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_user_email_lower', 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.alter_column('webhook', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'generic'::character varying"))
    op.alter_column('webhook', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('webhook', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('webhook', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('workflow', 'graph_definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_workflow_status'), 'workflow', ['status'], unique=False)
    op.create_index('ix_workflow_user_status', 'workflow', ['user_id', 'status'], unique=False)
    op.create_index('ix_workflow_user_updated', 'workflow', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_execution_status_started', 'workflowexecution', ['status', 'started_at'], unique=False)
    op.create_index('ix_execution_workflow_started', 'workflowexecution', ['workflow_id', 'started_at'], unique=False)
    op.create_index('ix_execution_workflow_status', 'workflowexecution', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflowexecution_status'), 'workflowexecution', ['status'], unique=False)
    op.add_column('workflowmemory', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('workflowmemory', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.add_column('workflowmemory', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('workflowmemory', sa.Column('is_summarized', sa.Boolean(), nullable=True))
    op.add_column('workflowmemory', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('workflowmemory', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('workflowmemory', 'metadata_json',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('workflowmemory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_memory_conversation_created', 'workflowmemory', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_memory_conversation_sequence', 'workflowmemory', ['conversation_id', 'sequence_number'], unique=False)
    op.create_index('ix_memory_expires', 'workflowmemory', ['expires_at'], unique=False)
    op.create_index('ix_memory_workflow_conversation', 'workflowmemory', ['workflow_id', 'conversation_id'], unique=False)
    op.alter_column('workflowversion', 'graph_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index('ix_version_workflow_number', 'workflowversion', ['workflow_id', 'version_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_version_workflow_number', table_name='workflowversion')
    op.alter_column('workflowversion', 'graph_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index('ix_memory_workflow_conversation', table_name='workflowmemory')
    op.drop_index('ix_memory_expires', table_name='workflowmemory')
    op.drop_index('ix_memory_conversation_sequence', table_name='workflowmemory')
    op.drop_index('ix_memory_conversation_created', table_name='workflowmemory')
    op.alter_column('workflowmemory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('workflowmemory', 'metadata_json',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('workflowmemory', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('workflowmemory', 'expires_at')
    op.drop_column('workflowmemory', 'is_summarized')
    op.drop_column('workflowmemory', 'is_pinned')
    op.drop_column('workflowmemory', 'sequence_number')
    op.drop_column('workflowmemory', 'token_count')
    op.drop_index(op.f('ix_workflowexecution_status'), table_name='workflowexecution')
    op.drop_index('ix_execution_workflow_status', table_name='workflowexecution')
    op.drop_index('ix_execution_workflow_started', table_name='workflowexecution')
    op.drop_index('ix_execution_status_started', table_name='workflowexecution')
    op.drop_index('ix_workflow_user_updated', table_name='workflow')
    op.drop_index('ix_workflow_user_status', table_name='workflow')
    op.drop_index(op.f('ix_workflow_status'), table_name='workflow')
    op.alter_column('workflow', 'graph_definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('webhook', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('webhook', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('webhook', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('webhook', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'generic'::character varying"))
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index('ix_user_email_lower', table_name='user')
    op.drop_index('ix_user_active_created', table_name='user')
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_trace_node_status', table_name='nodeexecutiontrace')
    op.drop_index('ix_trace_execution_created', table_name='nodeexecutiontrace')
    op.alter_column('nodeexecutiontrace', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_knowledgedocument_filename'), table_name='knowledgedocument')
    op.drop_index('ix_knowledge_user_filename', table_name='knowledgedocument')
    op.drop_index('ix_knowledge_filename_chunk', table_name='knowledgedocument')
    op.drop_index('ix_knowledge_content_hash', table_name='knowledgedocument')
    op.alter_column('knowledgedocument', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('knowledgedocument', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('knowledgedocument', 'updated_at')
    op.drop_column('knowledgedocument', 'word_count')
    op.drop_column('knowledgedocument', 'char_count')
    op.drop_column('knowledgedocument', 'embedding_model')
    op.drop_column('knowledgedocument', 'metadata_json')
    op.drop_column('knowledgedocument', 'content_hash')
    op.drop_column('knowledgedocument', 'total_chunks')
    op.alter_column('connection', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_user_quotas_user_id'), table_name='user_quotas')
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_usage_records_workflow_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_execution_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index('idx_usage_workflow', table_name='usage_records')
    op.drop_index('idx_usage_user_created', table_name='usage_records')
    op.drop_index('idx_usage_provider_model', table_name='usage_records')
    op.drop_index('idx_usage_execution', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_monthly_usage_summaries_user_id'), table_name='monthly_usage_summaries')
    op.drop_index('idx_monthly_user_period', table_name='monthly_usage_summaries')
    op.drop_table('monthly_usage_summaries')
    # ### end Alembic commands ###
