"""Add Memory and RAG Vector tables

Revision ID: 4dd6b27a4d41
Revises: e18c5e4bf740
Create Date: 2025-12-20 06:34:13.351152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4dd6b27a4d41'
down_revision: Union[str, Sequence[str], None] = 'e18c5e4bf740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('knowledgedocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgedocument_user_id'), 'knowledgedocument', ['user_id'], unique=False)
    op.create_table('workflowmemory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowmemory_conversation_id'), 'workflowmemory', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_workflowmemory_workflow_id'), 'workflowmemory', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflowmemory_workflow_id'), table_name='workflowmemory')
    op.drop_index(op.f('ix_workflowmemory_conversation_id'), table_name='workflowmemory')
    op.drop_table('workflowmemory')
    op.drop_index(op.f('ix_knowledgedocument_user_id'), table_name='knowledgedocument')
    op.drop_table('knowledgedocument')
    # ### end Alembic commands ###
