"""Add engine metadata and versioning

Revision ID: 5362b7633307
Revises: 0dfa49bde271
Create Date: 2025-12-23 15:27:29.549521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5362b7633307'
down_revision: Union[str, Sequence[str], None] = '0dfa49bde271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nodeexecutiontrace_execution_id'), 'nodeexecutiontrace', ['execution_id'], unique=False)
    op.create_index(op.f('ix_nodeexecutiontrace_node_id'), 'nodeexecutiontrace', ['node_id'], unique=False)
    op.create_index(op.f('ix_webhook_workflow_id'), 'webhook', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_version_id'), 'workflowexecution', ['version_id'], unique=False)
    op.create_index(op.f('ix_workflowversion_version_number'), 'workflowversion', ['version_number'], unique=False)
    op.create_index(op.f('ix_workflowversion_workflow_id'), 'workflowversion', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflowversion_workflow_id'), table_name='workflowversion')
    op.drop_index(op.f('ix_workflowversion_version_number'), table_name='workflowversion')
    op.drop_index(op.f('ix_workflowexecution_version_id'), table_name='workflowexecution')
    op.drop_index(op.f('ix_webhook_workflow_id'), table_name='webhook')
    op.drop_index(op.f('ix_nodeexecutiontrace_node_id'), table_name='nodeexecutiontrace')
    op.drop_index(op.f('ix_nodeexecutiontrace_execution_id'), table_name='nodeexecutiontrace')
    # ### end Alembic commands ###
