"""add_workflow_api_table

Revision ID: 548d7155be22
Revises: 42a6dc963da9
Create Date: 2026-06-19 12:15:14.477810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '548d7155be22'
down_revision: Union[str, Sequence[str], None] = '42a6dc963da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_next_run_active'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_next_run_at'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_status'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_user_id'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_user_status'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_workflow_id'), table_name='workflow_schedule')
    op.drop_index(op.f('ix_schedule_workflow_status'), table_name='workflow_schedule')
    op.drop_table('workflow_schedule')
    op.drop_index(op.f('ix_memory_conversation_created'), table_name='workflowmemory')
    op.drop_index(op.f('ix_memory_conversation_sequence'), table_name='workflowmemory')
    op.drop_index(op.f('ix_memory_expires'), table_name='workflowmemory')
    op.drop_index(op.f('ix_memory_workflow_conversation'), table_name='workflowmemory')
    op.drop_index(op.f('ix_workflowmemory_conversation_id'), table_name='workflowmemory')
    op.drop_index(op.f('ix_workflowmemory_workflow_id'), table_name='workflowmemory')
    op.drop_table('workflowmemory')
    op.drop_index(op.f('ix_version_workflow_number'), table_name='workflowversion')
    op.drop_index(op.f('ix_workflowversion_version_number'), table_name='workflowversion')
    op.drop_index(op.f('ix_workflowversion_workflow_id'), table_name='workflowversion')
    op.drop_table('workflowversion')
    op.drop_index(op.f('ix_nodeexecutiontrace_execution_id'), table_name='nodeexecutiontrace')
    op.drop_index(op.f('ix_nodeexecutiontrace_node_id'), table_name='nodeexecutiontrace')
    op.drop_index(op.f('ix_trace_execution_created'), table_name='nodeexecutiontrace')
    op.drop_index(op.f('ix_trace_node_status'), table_name='nodeexecutiontrace')
    op.drop_table('nodeexecutiontrace')
    op.drop_index(op.f('ix_connection_provider'), table_name='connection')
    op.drop_index(op.f('ix_connection_user_active'), table_name='connection')
    op.drop_index(op.f('ix_connection_user_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_user_provider'), table_name='connection')
    op.drop_table('connection')
    op.drop_index(op.f('ix_knowledge_content_hash'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledge_filename_chunk'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledge_user_filename'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_filename'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_user_id'), table_name='knowledgedocument')
    op.drop_table('knowledgedocument')
    op.drop_index(op.f('idx_monthly_user_period'), table_name='monthly_usage_summaries')
    op.drop_index(op.f('ix_monthly_usage_summaries_user_id'), table_name='monthly_usage_summaries')
    op.drop_table('monthly_usage_summaries')
    op.drop_index(op.f('ix_template_category'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_category_featured'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_clone_count'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_is_featured'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_is_public'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_public_featured'), table_name='workflow_template')
    op.drop_index(op.f('ix_template_user_id'), table_name='workflow_template')
    op.drop_table('workflow_template')
    op.drop_index(op.f('ix_webhook_slug'), table_name='webhook')
    op.drop_index(op.f('ix_webhook_status'), table_name='webhook')
    op.drop_index(op.f('ix_webhook_workflow_active'), table_name='webhook')
    op.drop_index(op.f('ix_webhook_workflow_id'), table_name='webhook')
    op.drop_table('webhook')
    op.drop_index(op.f('idx_usage_execution'), table_name='usage_records')
    op.drop_index(op.f('idx_usage_provider_model'), table_name='usage_records')
    op.drop_index(op.f('idx_usage_user_created'), table_name='usage_records')
    op.drop_index(op.f('idx_usage_workflow'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_execution_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_workflow_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_user_active_created'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_email_lower'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_user_quotas_user_id'), table_name='user_quotas')
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_execution_status_started'), table_name='workflowexecution')
    op.drop_index(op.f('ix_execution_workflow_started'), table_name='workflowexecution')
    op.drop_index(op.f('ix_execution_workflow_status'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_external_event_id'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_status'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_version_id'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_workflow_id'), table_name='workflowexecution')
    op.drop_table('workflowexecution')
    op.drop_index(op.f('ix_workflow_status'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_user_id'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_user_status'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_user_updated'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('graph_definition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='workflowstatus'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('active_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('global_variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workflow_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_pkey'))
    )
    op.create_index(op.f('ix_workflow_user_updated'), 'workflow', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_workflow_user_status'), 'workflow', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_user_id'), 'workflow', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_status'), 'workflow', ['status'], unique=False)
    op.create_table('workflowexecution',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='executionstatus'), autoincrement=False, nullable=False),
    sa.Column('graph_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('external_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['workflowversion.id'], name=op.f('workflowexecution_version_id_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('workflowexecution_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflowexecution_pkey'))
    )
    op.create_index(op.f('ix_workflowexecution_workflow_id'), 'workflowexecution', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_version_id'), 'workflowexecution', ['version_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_status'), 'workflowexecution', ['status'], unique=False)
    op.create_index(op.f('ix_workflowexecution_external_event_id'), 'workflowexecution', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_execution_workflow_status'), 'workflowexecution', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_execution_workflow_started'), 'workflowexecution', ['workflow_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_execution_status_started'), 'workflowexecution', ['status', 'started_at'], unique=False)
    op.create_table('user_quotas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('monthly_token_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthly_execution_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthly_cost_limit_usd', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('current_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_executions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_cost_usd', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_quotas_pkey'))
    )
    op.create_index(op.f('ix_user_quotas_user_id'), 'user_quotas', ['user_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_email_lower'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_active_created'), 'user', ['is_active', 'created_at'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_records_pkey'))
    )
    op.create_index(op.f('ix_usage_records_workflow_id'), 'usage_records', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_records_execution_id'), 'usage_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('idx_usage_workflow'), 'usage_records', ['workflow_id'], unique=False)
    op.create_index(op.f('idx_usage_user_created'), 'usage_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_usage_provider_model'), 'usage_records', ['provider', 'model'], unique=False)
    op.create_index(op.f('idx_usage_execution'), 'usage_records', ['execution_id'], unique=False)
    op.create_table('webhook',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secret_key_rotated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), server_default=sa.text("'generic'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('rate_limit', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('rate_limit_window', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rate_limit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('allowed_ips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_triggers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_triggers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('consecutive_failures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('config_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('webhook_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_pkey'))
    )
    op.create_index(op.f('ix_webhook_workflow_id'), 'webhook', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_webhook_workflow_active'), 'webhook', ['workflow_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_webhook_status'), 'webhook', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_slug'), 'webhook', ['slug'], unique=True)
    op.create_table('workflow_template',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('AI Automation', 'Data Processing', 'Communication', 'Marketing', 'Customer Support', 'Development', 'Productivity', 'Analytics', 'Getting Started', name='templatecategory'), server_default=sa.text("'Getting Started'::templatecategory"), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('graph_definition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('required_connections', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), server_default=sa.text("'Workflow'::character varying"), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), server_default=sa.text("'beginner'::character varying"), autoincrement=False, nullable=False),
    sa.Column('estimated_setup_minutes', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('clone_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workflow_template_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_template_pkey'))
    )
    op.create_index(op.f('ix_template_user_id'), 'workflow_template', ['user_id'], unique=False)
    op.create_index(op.f('ix_template_public_featured'), 'workflow_template', ['is_public', 'is_featured'], unique=False)
    op.create_index(op.f('ix_template_is_public'), 'workflow_template', ['is_public'], unique=False)
    op.create_index(op.f('ix_template_is_featured'), 'workflow_template', ['is_featured'], unique=False)
    op.create_index(op.f('ix_template_clone_count'), 'workflow_template', ['clone_count'], unique=False)
    op.create_index(op.f('ix_template_category_featured'), 'workflow_template', ['category', 'is_featured'], unique=False)
    op.create_index(op.f('ix_template_category'), 'workflow_template', ['category'], unique=False)
    op.create_table('monthly_usage_summaries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_executions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cost_usd', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('usage_by_provider', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('top_workflows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('monthly_usage_summaries_pkey'))
    )
    op.create_index(op.f('ix_monthly_usage_summaries_user_id'), 'monthly_usage_summaries', ['user_id'], unique=False)
    op.create_index(op.f('idx_monthly_user_period'), 'monthly_usage_summaries', ['user_id', 'period_year', 'period_month'], unique=False)
    op.create_table('knowledgedocument',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('char_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledgedocument_pkey'))
    )
    op.create_index(op.f('ix_knowledgedocument_user_id'), 'knowledgedocument', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_filename'), 'knowledgedocument', ['filename'], unique=False)
    op.create_index(op.f('ix_knowledge_user_filename'), 'knowledgedocument', ['user_id', 'filename'], unique=False)
    op.create_index(op.f('ix_knowledge_filename_chunk'), 'knowledgedocument', ['filename', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledge_content_hash'), 'knowledgedocument', ['content_hash'], unique=False)
    op.create_table('connection',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_credentials', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('use_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('connection_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_pkey'))
    )
    op.create_index(op.f('ix_connection_user_provider'), 'connection', ['user_id', 'provider'], unique=False)
    op.create_index(op.f('ix_connection_user_id'), 'connection', ['user_id'], unique=False)
    op.create_index(op.f('ix_connection_user_active'), 'connection', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_connection_provider'), 'connection', ['provider'], unique=False)
    op.create_table('nodeexecutiontrace',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflowexecution.id'], name=op.f('nodeexecutiontrace_execution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nodeexecutiontrace_pkey'))
    )
    op.create_index(op.f('ix_trace_node_status'), 'nodeexecutiontrace', ['node_id', 'status'], unique=False)
    op.create_index(op.f('ix_trace_execution_created'), 'nodeexecutiontrace', ['execution_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_nodeexecutiontrace_node_id'), 'nodeexecutiontrace', ['node_id'], unique=False)
    op.create_index(op.f('ix_nodeexecutiontrace_execution_id'), 'nodeexecutiontrace', ['execution_id'], unique=False)
    op.create_table('workflowversion',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('graph_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('workflowversion_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflowversion_pkey'))
    )
    op.create_index(op.f('ix_workflowversion_workflow_id'), 'workflowversion', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowversion_version_number'), 'workflowversion', ['version_number'], unique=False)
    op.create_index(op.f('ix_version_workflow_number'), 'workflowversion', ['workflow_id', 'version_number'], unique=True)
    op.create_table('workflowmemory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_summarized', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workflowmemory_pkey'))
    )
    op.create_index(op.f('ix_workflowmemory_workflow_id'), 'workflowmemory', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowmemory_conversation_id'), 'workflowmemory', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_workflow_conversation'), 'workflowmemory', ['workflow_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_expires'), 'workflowmemory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memory_conversation_sequence'), 'workflowmemory', ['conversation_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_memory_conversation_created'), 'workflowmemory', ['conversation_id', 'created_at'], unique=False)
    op.create_table('workflow_schedule',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('schedule_type', postgresql.ENUM('CRON', 'INTERVAL', 'ONCE', name='scheduletype'), server_default=sa.text("'CRON'::scheduletype"), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'DISABLED', 'COMPLETED', name='schedulestatus'), server_default=sa.text("'ACTIVE'::schedulestatus"), autoincrement=False, nullable=False),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_execution_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('run_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('consecutive_errors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True),
    sa.Column('max_consecutive_errors', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workflow_schedule_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('workflow_schedule_workflow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_schedule_pkey'))
    )
    op.create_index(op.f('ix_schedule_workflow_status'), 'workflow_schedule', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedule_workflow_id'), 'workflow_schedule', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_schedule_user_status'), 'workflow_schedule', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedule_user_id'), 'workflow_schedule', ['user_id'], unique=False)
    op.create_index(op.f('ix_schedule_status'), 'workflow_schedule', ['status'], unique=False)
    op.create_index(op.f('ix_schedule_next_run_at'), 'workflow_schedule', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_next_run_active'), 'workflow_schedule', ['next_run_at', 'status'], unique=False)
    # ### end Alembic commands ###
