import enum

class ErrorCodes(enum.StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    API_KEY_INVALID_ERROR = "API_KEY_INVALID_ERROR"
    RESPONSE_GENERATION_ERROR = "RESPONSE_GENERATION_ERROR"
    CLIENT_CHAT_COMPLETION_ERROR = "CLIENT_CHAT_COMPLETION_ERROR"
    MODEL_NOT_EXIST = "MODEL_NOT_EXIST"
    RESPONSE_PARSE_FAILED = "RESPONSE_PARSE_FAILED"
    IMAGE_GENERATION_ERROR = "IMAGE_GENERATION_ERROR"
    SPEECH_GENERATION_CLIENT_ERROR = "SPEECH_GENERATION_CLIENT_ERROR"
    SPEECH_GENERATION_ERROR = "SPEECH_GENERATION_ERROR"
    VIDEO_GENERATION_CLIENT_ERROR = "VIDEO_GENERATION_CLIENT_ERROR"
    VIDEO_GENERATION_ERROR = "VIDEO_GENERATION_ERROR"
